server:
  port: 80

spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://sql.s1166.vhostgo.com/htmboy?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: htmboy
    password: Htmboy8msn.com